### ISSUE TITLE
Crash on opening settings menu

### ISSUE THREAD

**Issue by TMCAtom** [MaliciousFiles/EditPlayerData#16] opened 2024-10-04 18:08 UTC
Game simply crashes without any popup windows or notifications when opening the settings menu, i have installed the most recent version of BTD6 Mod Helper, please advise.

**Comment by MaliciousFiles** [comment] 2024-10-04 19:10
I cannot reproduce, it appears to work as intended when using the following two DLLs:

[https://github.com/MaliciousFiles/EditPlayerData/releases/download/v1.3.3/EditPlayerData.dll](https://github.com/MaliciousFiles/EditPlayerData/releases/download/v1.3.3/EditPlayerData.dll)
[https://github.com/gurrenm3/BTD-Mod-Helper/releases/download/3.2.1/Btd6ModHelper.dll](https://github.com/gurrenm3/BTD-Mod-Helper/releases/download/3.2.1/Btd6ModHelper.dll)

Please confirm that there are no other mods installed, you are on the latest version of BTD6, and you are using these two DLL files. If you are still experiencing the issue, please upload the following log file: `BloonsTD6/MelonLoader/Latest.log`. You can find the BloonsTD6 folder by right clicking on it in Steam, and selecting "Manage > Browse local files".

**Comment by MaliciousFiles** [comment] 2024-10-04 20:37
Yeah looks like you're using MelonLoader `v0.6.0 ALPHA`, try downloading the installer at [https://github.com/HerpDerpinstine/MelonLoader/releases/latest/download/MelonLoader.Installer.exe](https://github.com/HerpDerpinstine/MelonLoader/releases/latest/download/MelonLoader.Installer.exe) and installing whatever the latest is (I think it's 0.6.5, but the installer should say). 

Side note: looks like the error that's causing the crash is in the Mod Helper rather than EditPlayerData, but updating MelonLoader will probably fix it.

**Comment by TMCAtom** [comment] 2024-10-04 21:31
after installing version 0.6.5 open beta it seems to still not be working, even with all other mods removed i simply cannot open the settings menu for some reason,  [here](https://github.com/user-attachments/files/17263926/Latest.log) is my log, hope you can find something.

**Comment by MaliciousFiles** [comment] 2024-10-04 22:16
Weird. I don't see any errors in the log. If there is a `MelonLoader/Logs` folder, attach the latest log in there. It probably has something to do with running it through Wine, though I'm not sure what. If you have access to a Windows computer (or can partition your drive), you could use the mod to edit your player data there, and then the edits should populate on your Debian install.

**Comment by TMCAtom** [comment] 2024-10-05 18:44
thats certainly an option, though that means that this is actually the first time my OS actually caused a mod to not work, excluding mods that require windows only programs like cheat engine to run. so im not really sure if this is the case, considering all other cases of mods working.

**Comment by MaliciousFiles** [comment] 2024-10-12 03:57
You can try to see if the [latest version](https://github.com/MaliciousFiles/EditPlayerData/releases/tag/v1.3.4) of the mod works. If not, I don't really have any other ideas (and don't have the time to test it on Debian myself).

**Comment by MaliciousFiles** [comment] 2024-10-14 18:09
I'm going to close this thread for now. If there are any new developments, feel free to re-open/create a new issue.

**Closed by MaliciousFiles** 2024-10-14 18:09 UTC
